// <auto-generated />

using System;
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SynchroFeed.Command.Catalog.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropHash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropHash));
        
        string IMigrationMetadata.Id
        {
            get { return "201806240723422_DropHash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
