// <auto-generated />
namespace SynchroFeed.Command.Catalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    #pragma warning disable 1591

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateViews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateViews));
        
        string IMigrationMetadata.Id
        {
            get { return "201903040053065_CreateViews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
